#!/bin/bash

echo "🚀 Video Frame Extractor - iOS Build Helper"
echo "==========================================="
echo ""
echo "⚠️  IMPORTANT: Due to SDK version issues, please build from Xcode:"
echo ""
echo "1. Xcode should already be open with VideoFrameExtractor.xcworkspace"
echo "2. At the top of Xcode, click the device dropdown (next to 'VideoFrameExtractor')"
echo "3. Select any available iPhone simulator (e.g., 'iPhone 16 Pro')"
echo "4. Press Cmd+R to build and run"
echo ""
echo "The app will launch on the selected simulator!"
echo ""
echo "📱 Once running, you can:"
echo "  - Pick a video from the simulator"
echo "  - Choose FPS rate or 'All Frames'"
echo "  - Extract frames at original quality"
echo "  - Find screenshots in Documents/Screenshots/"
echo ""
echo "🔥 Metro bundler is running on port 8081 for hot reload"
echo ""
